name: coding-challenges
channels:
  - conda-forge
dependencies:
  # Use workflow matrix to override Python version
  - python
  - pip          # Always include pip
  - pytest       # For running tests
  - flake8       # For linting
  - colorama     # Optional, commonly used for CLI colors
  - typing_extensions
  - pip:
      - requests  # Add your pip packages here
      - black     # Optional code formatter
